version: "3.2"
services:
  redis:
    image: redis
    container_name: cache
    command: ["redis-server", "--appendonly", "yes"]
    environment:
      - REDIS_URL=redis://cache
    volumes:
      - ./redis-data:/data
      #- ./redis-data:/usr/local/etc/redis/data # is this correct data folder
      # - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    expose:
      - 6379
    restart: always
    networks:
      - docker-network
networks:
  docker-network:
    driver: bridge
